title: Researcher
url: "darthbarth.science"
baseurl: "/home"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/mjyb16"
footer_text: "Page design by Ankit Sultana and M. J. Yantovski-Barth"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
