title: M. J. Yantovski-Barth
url: "/"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/mjyb16/mjyb16.github.io"
footer_text: "Page design by Ankit Sultana, Tim Holman, and M. J. Yantovski-Barth"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Research"
   link: "research"
 - name: "Software"
   link: "software"
 - name: "Teaching + Outreach"
   link: "teaching"
 - name: "Blog"
   link: "blog"
 - name: "CV"
   link: "CV_MICHAEL_BARTH_June_2025.pdf"
 - name: "Contact"
   link: "contact"
 
